### ISSUE TITLE
strchr??

### ISSUE THREAD

**Issue by mertekren** [BrianNormant/aoc2023#1]
it's not important but the way you use strchr in day13 is very weird, and i dont know how it does even compile.

**Comment by BrianNormant** [comment]
I didn't think anyone would actually look at this repo, thanks.

```c
*strchr(buf, '\n') = '\0';
```
Honestly, I don't remember why I used it like that. I just wanted to remove the newline. So replacing the first '\n' with a '\0' would do the trick.
I randomly use strsep, strtok_r, and ` line[len-1] = '\0' ` depending of my mood I guess.

I make sense that it compiles:
strchar(...) return a char* pointing to the first /n in the string.
\* dereference this pointer, and = '\0' to set it to null.

Not the most readable, I do agree.
Other people seems to do this is C using
```c
int i = 0;
while (line[i++] != '\n');
line[i] = '\0'
```
Which is what my code utimatly does.
edit: typo

**Comment by mertekren** [comment]
Thanks for the explanation good luck on 2024 aoc.
